# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73cdc2dcf8af666118ad9ceef2150e2e3b19868d811015ad3c640acfd37560e24c8e55f8216dad6e8b091e77c1afaf424aeb486d3758554f95279d8397a3ebfb

test:
  secret_key_base: f5db6567e949e4065d0fdc763eaf3f6eccc6ec4c28f300dcf8c0439fa5922f99da29d5ce7633fd2e1f0f929c3ffaf977b4113f0f13439cf1be17987bf2a3eceb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
